[[main]]
  identifier = "lang"
  name = "Lang"
  url = "/en/lang/readme/"
  weight = 100

[[main]]
  identifier = "linux"
  name = "Linux"
  url = "/en/linux/readme/"
  weight = 200

[[main]]
  identifier = "cloud"
  name = "Cloud"
  url = "/en/cloud/readme/"
  weight = 300

[[footer]]
  name = "粤ICP备2024312555号-1"
  url = "https://beian.miit.gov.cn/"
  weight = 10
