[[main]]
  identifier = "lang"
  name = "Lang"
  url = "/zh-cn/lang/readme/"
  weight = 100

[[main]]
  identifier = "linux"
  name = "Linux"
  url = "/zh-cn/linux/readme/"
  weight = 200

[[main]]
  identifier = "database"
  name = "Database"
  url = "/zh-cn/database/readme/"
  weight = 300

[[main]]
  identifier = "cloud"
  name = "Cloud"
  url = "/zh-cn/cloud/readme/"
  weight = 400

[[main]]
  identifier = "snippets"
  name = "Snippets"
  url = "/zh-cn/snippets/readme/"
  weight = 500

[[footer]]
  name = "粤ICP备2024312555号-1"
  url = "https://beian.miit.gov.cn/"
  weight = 10

# lang sidebar

[[sidebar_lang]]
  name = "README"
  pageRef = "/lang/readme/"
  weight = 100

[[sidebar_lang]]
  name = "MEME"
  pageRef = "/lang/meme/"
  weight = 200

[[sidebar_lang]]
  name = "Go"
  pageRef = "/lang/go/"
  weight = 300

# linux sidebar

[[sidebar_linux]]
  name = "README"
  pageRef = "/linux/readme/"
  weight = 100

[[sidebar_linux]]
  name = "MEME"
  pageRef = "/linux/meme/"
  weight = 200

[[sidebar_linux]]
  name = "Say My Name"
  pageRef = "/linux/say-my-name/"
  weight = 300

# database sidebar

[[sidebar_database]]
  name = "README"
  pageRef = "/database/readme/"
  weight = 100

[[sidebar_database]]
  name = "MySQL"
  pageRef = "/database/mysql/"
  weight = 200

# cloud sidebar

[[sidebar_cloud]]
  name = "README"
  pageRef = "/cloud/readme/"
  weight = 100

# snippets sidebar

[[sidebar_snippets]]
  name = "README"
  pageRef = "/snippets/readme/"
  weight = 100

[[sidebar_snippets]]
  name = "MISC"
  pageRef = "/snippets/misc/"
  weight = 200
